BASE_TASK_CONFIG_PATH: ../HASimulator/config/HAVLNCE_task_internnav.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1
  EVAL_NONLEARNING: False

INFERENCE:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  INFERENCE_NONLEARNING: False
